### ISSUE TITLE
UnboundLocalError: local variable 'code' referenced before assignment

### ISSUE THREAD

**Issue by lou112ep** [Frocioccolato/UnieuroBot#2]
After launching your script, it returns these two errors. I'm running python 3.8.6
  
  - File "Main.py", line 43, in <module>
    res=Check.check_price(budget[j], link[j], email, pwd, gMailF, pMailF, gMailT)
  - File "/home/user/UnieuroBot/Unieuro/Check.py", line 146, in check_price
    data[input_tag["name"]] = code or ""
UnboundLocalError: local variable 'code' referenced before assignment

**Comment by carlott0** [comment]
I will fix it in the next few days, if you want to fix it yourself you have to add this line to line number 132 of Check.py
![Screenshot_20210403-211657](https://user-images.githubusercontent.com/49305804/113489046-131a7780-94c2-11eb-8293-c5a93c1614eb.jpg)
: code = "" You need to add this line to the line just before response = (request.get (link ... This error is due to the fact that the product is not available, so this additional line warns you that the product cannot be purchased. 
![Screenshot_20210403-211455](https://user-images.githubusercontent.com/49305804/113488997-cdf64580-94c1-11eb-93ee-595eb507dcf7.jpg)

**Comment by lou112ep** [comment]
It works! Thanks a lot!
